### ISSUE TITLE
Sass support for styles.css

### ISSUE THREAD

**Issue by baringji** [tsquez/wp-forge#30]
It would be best if we could have a sass files for styles.css

**Comment by tsquez** [comment]
Hi baringji,

Maybe once WP-Forge gets added to the WordPress theme directory but then again adding sass is a very big maybe. Not everyone uses sass. I for one do not. I would like to learn it but at this point in time I am comfortable where I am at and I am in no rush to learn. Maybe two versions, one that is regular and one that is sassified. Who knows, maybe, we will just have to wait and see.

**Comment by tsquez** [comment]
Hi again baringji,

I have been thinking about this since you posted it and I think that maybe we could go for two versions. I have looked at some of the other themes that mix WordPress and Foundation and quite a few do have a sass version as well as a regular css version.

I think that maybe this could be the way to go, but then again I don't know if I want to maintain two diff versions. How about we discuss this in more detail once WP-Forge is done with the review process. What do you think?

**Comment by baringji** [comment]
It would be nice. We can have two versions for the meantime (after the review process (wink)). I know lots of supporters would love this feature. Yeah, it's your call man. This is a big feature you know, having it implemented would be a pain in the a** but everything would come easier.

**Comment by tsquez** [comment]
Yeah I hear yah. Since day one, people have asked me about sass and WP-Forge. I know there is one theme in the directory that has sass and that's planet foundation.

As I mentioned before I think having two versions would be a pain in the end, so I am thinking just keep going the way I have been going. No sense in doubling up and creating more work. And yes, this needs to wait until after the review process with WP-Forge. I submitted WP-Forge 5 weeks ago for review and they just now assigned it to someone...lol

So if we are going to do this then I guess I had better start reading up on this sass and how to use it...lol

**Comment by tsquez** [comment]
I am still waiting to have WP-Forge reviewed. It was assigned a reviewer three weeks ago and I have not heard anything. Once this gets finished, I'd like to chat with you about throwing sass into the mix :wink:

**Comment by szabeszg** [comment]
Well, for the time being, I just add the required files to the child theme and update them when you update Foundation.
