### ISSUE TITLE
Header Width Scrolls

### ISSUE THREAD

**Issue by badcat** [tsquez/wp-forge#40]
There's an issue with horizontal scrolling with the <header> when using a Header image while removing the Site Title and Tagline. 

The .header-info class is then collapsing to  0 x 0 px, but the h1 .site-title class still renders a width which make the site exhibit horizontal scrolling.  The Header Wrapper is still the default 64rem. 

![site-title](https://cloud.githubusercontent.com/assets/26096/6802705/f5cf1e7e-d208-11e4-8328-35c26fd0fc4f.png)

**Comment by tsquez** [comment]
I see what you are talking about however I do not experience any horizontal scrolling. I tried it in IE, FF, Safari and Chrome (Windows environment). I do believe that it may be due to the way it is coded to be hidden. When you hide the text in the header the following gets applied:

```
   .site-title, .site-title a, .site-description {
   clip': rect(1px, 1px, 1px, 1px),
   position: absolute;
}
```
I am going to correct this in the upcoming version and just apply `display:none`, combined with `text-indent:-625rem;`

Thanks for bringing this up :wink:
