### ISSUE TITLE
Top Bar mobile sticky

### ISSUE THREAD

**Issue by marvinsss2005** [tsquez/wp-forge#45]
Hi,

Is there a way in mobile mode to make the top bar sticky or fixed?

Thanks...

**Comment by tsquez** [comment]
Hey there, unfortunately this is not something that has been asked for before, so I have never looked into it. It also concerns the Foundation portion of the theme, so you may want to look at the Foundation forums and see if anyone has asked the same question.

**Comment by marvinsss2005** [comment]
Hi,

Finally found a way, just noticed that the off canvass has no fixed feature so what i did was used the nav/top-bar from small to large devices and hide off-canvas from small to large devices.

Thanks...

**Comment by tsquez** [comment]
Awesome, can you explain what you did so maybe someone else who may be
interested in accomplishing the same thing may be able to do it. If you can
that would be great.

On Fri, May 8, 2015 at 1:10 PM, marvinsss2005 <notifications@github.com>
wrote:

> Hi,
>
> Finally found a way, just noticed that the off canvass has no fixed
> feature so what i did was used the nav/top-bar from small to large devices
> and hide off-canvas from small to large devices.
>
> Thanks...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsquez/wp-forge/issues/45#issuecomment-100345450>.
>



-- 
Thomas E. Vasquez
Freelance WordPress Theme Support
ThemeAwesome.com <http://themeawesome.com>
Skype: tsquez

**Comment by marvinsss2005** [comment]
Hi,

In content-nav.php i removed the hide-for-small-only in line 158 for sticky and for content-off_canvas.php i changed line 17 to hide-for-small-up. When i reviewed Foundation Docs there is no hide-for-small-up class but it's working so it exist?

Thanks...

**Comment by tsquez** [comment]
Hey there,

you have to remember that WP-Forge was born waaaaaaaaaaaaaaaaaaaay back
with Foundation 3 and uses snippets of code from a few other themes as
well. So that class may be something from there, I have no idea and I can't
remember why its there, but yes it seems to be working. I think that it may
even have been here at one time
http://foundation.zurb.com/docs/components/visibility.html

On Fri, May 8, 2015 at 4:39 PM, marvinsss2005 <notifications@github.com>
wrote:

> Hi,
>
> In content-nav.php i removed the hide-for-small-only in line 158 for
> sticky and for content-off_canvas.php i changed line 17 to
> hide-for-small-up. When i reviewed Foundation Docs there is no
> hide-for-small-up class but it's working so it exist?
>
> Thanks...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsquez/wp-forge/issues/45#issuecomment-100394549>.
>



-- 
Thomas E. Vasquez
Freelance WordPress Theme Support
ThemeAwesome.com <http://themeawesome.com>
Skype: tsquez
