### ISSUE TITLE
Wish List Item

### ISSUE THREAD

**Issue by Techdoode** [tsquez/wp-forge#46]
I'm not well versed in GitHub, so forgive me if I'm violating protocol.  If this is not the right way to carry on this kind of discussion, please let me know the proper way.  :-)

I would love to see SiteOrigin's Page Builder WordPress plugin speak Foundation:  https://siteorigin.com/page-builder/

I have pro-bono client at my church who are not coders and am casting about for a way NOT to be involved in every update to their website.  The plugin seems to play well with wp-forge, but does not use Foundation.  

I'm attempting to analyze the plugin code, but my coding skills are admittedly not the best.

Any thoughts?

Best regards,
Nick

**Comment by badcat** [comment]
This sounds like you'd need to get Greg from SiteOrigin involved.  I'd love for Page Builder to "speak" Foundation too since it'd probably lighten up the CSS he currently has in PB - but I'd doubt it since there's tons more "flexibility" (i.e., custom percentages etc) in PB that Foundation does not use.
